package pb;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbtest.proto

public final class Pbtest {
  private Pbtest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface gps_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gps_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string terminalId = 2;</code>
     */
    java.lang.String getTerminalId();
    /**
     * <code>string terminalId = 2;</code>
     */
    com.google.protobuf.ByteString
        getTerminalIdBytes();

    /**
     * <code>string dataTime = 3;</code>
     */
    java.lang.String getDataTime();
    /**
     * <code>string dataTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataTimeBytes();

    /**
     * <code>double lon = 4;</code>
     */
    double getLon();

    /**
     * <code>double lat = 5;</code>
     */
    double getLat();

    /**
     * <code>float speed = 6;</code>
     */
    float getSpeed();

    /**
     * <code>int32 altitude = 7;</code>
     */
    int getAltitude();

    /**
     * <code>int32 locType = 8;</code>
     */
    int getLocType();

    /**
     * <code>int32 gpsStatus = 9;</code>
     */
    int getGpsStatus();

    /**
     * <code>float direction = 10;</code>
     */
    float getDirection();

    /**
     * <code>int32 satellite = 11;</code>
     */
    int getSatellite();

    /**
     * <code>int64 testField1 = 12;</code>
     */
    long getTestField1();

    /**
     * <code>.gps_data.LocationXY locXY = 13;</code>
     */
    boolean hasLocXY();
    /**
     * <code>.gps_data.LocationXY locXY = 13;</code>
     */
    Pbtest.gps_data.LocationXY getLocXY();
    /**
     * <code>.gps_data.LocationXY locXY = 13;</code>
     */
    Pbtest.gps_data.LocationXYOrBuilder getLocXYOrBuilder();

    /**
     * <code>.gps_data.SatelliteType satelliteType = 14;</code>
     */
    int getSatelliteTypeValue();
    /**
     * <code>.gps_data.SatelliteType satelliteType = 14;</code>
     */
    Pbtest.gps_data.SatelliteType getSatelliteType();

    /**
     * <code>repeated int32 xys = 15;</code>
     */
    java.util.List<java.lang.Integer> getXysList();
    /**
     * <code>repeated int32 xys = 15;</code>
     */
    int getXysCount();
    /**
     * <code>repeated int32 xys = 15;</code>
     */
    int getXys(int index);
  }
  /**
   * Protobuf type {@code gps_data}
   */
  public  static final class gps_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gps_data)
      gps_dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gps_data.newBuilder() to construct.
    private gps_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gps_data() {
      id_ = 0L;
      terminalId_ = "";
      dataTime_ = "";
      lon_ = 0D;
      lat_ = 0D;
      speed_ = 0F;
      altitude_ = 0;
      locType_ = 0;
      gpsStatus_ = 0;
      direction_ = 0F;
      satellite_ = 0;
      testField1_ = 0L;
      satelliteType_ = 0;
      xys_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gps_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              terminalId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dataTime_ = s;
              break;
            }
            case 33: {

              lon_ = input.readDouble();
              break;
            }
            case 41: {

              lat_ = input.readDouble();
              break;
            }
            case 53: {

              speed_ = input.readFloat();
              break;
            }
            case 56: {

              altitude_ = input.readInt32();
              break;
            }
            case 64: {

              locType_ = input.readInt32();
              break;
            }
            case 72: {

              gpsStatus_ = input.readInt32();
              break;
            }
            case 85: {

              direction_ = input.readFloat();
              break;
            }
            case 88: {

              satellite_ = input.readInt32();
              break;
            }
            case 96: {

              testField1_ = input.readInt64();
              break;
            }
            case 106: {
              Pbtest.gps_data.LocationXY.Builder subBuilder = null;
              if (locXY_ != null) {
                subBuilder = locXY_.toBuilder();
              }
              locXY_ = input.readMessage(Pbtest.gps_data.LocationXY.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(locXY_);
                locXY_ = subBuilder.buildPartial();
              }

              break;
            }
            case 112: {
              int rawValue = input.readEnum();

              satelliteType_ = rawValue;
              break;
            }
            case 120: {
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
                xys_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00004000;
              }
              xys_.add(input.readInt32());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000) && input.getBytesUntilLimit() > 0) {
                xys_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00004000;
              }
              while (input.getBytesUntilLimit() > 0) {
                xys_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
          xys_ = java.util.Collections.unmodifiableList(xys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pbtest.internal_static_gps_data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pbtest.internal_static_gps_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pbtest.gps_data.class, Pbtest.gps_data.Builder.class);
    }

    /**
     * Protobuf enum {@code gps_data.SatelliteType}
     */
    public enum SatelliteType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <code>GPS = 1;</code>
       */
      GPS(1),
      /**
       * <code>GLONASS = 2;</code>
       */
      GLONASS(2),
      /**
       * <code>GALILEO = 3;</code>
       */
      GALILEO(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <code>GPS = 1;</code>
       */
      public static final int GPS_VALUE = 1;
      /**
       * <code>GLONASS = 2;</code>
       */
      public static final int GLONASS_VALUE = 2;
      /**
       * <code>GALILEO = 3;</code>
       */
      public static final int GALILEO_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SatelliteType valueOf(int value) {
        return forNumber(value);
      }

      public static SatelliteType forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return GPS;
          case 2: return GLONASS;
          case 3: return GALILEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SatelliteType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SatelliteType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SatelliteType>() {
              public SatelliteType findValueByNumber(int number) {
                return SatelliteType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Pbtest.gps_data.getDescriptor().getEnumTypes().get(0);
      }

      private static final SatelliteType[] VALUES = values();

      public static SatelliteType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SatelliteType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:gps_data.SatelliteType)
    }

    public interface LocationXYOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gps_data.LocationXY)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string x = 1;</code>
       */
      java.lang.String getX();
      /**
       * <code>string x = 1;</code>
       */
      com.google.protobuf.ByteString
          getXBytes();

      /**
       * <code>string y = 2;</code>
       */
      java.lang.String getY();
      /**
       * <code>string y = 2;</code>
       */
      com.google.protobuf.ByteString
          getYBytes();
    }
    /**
     * Protobuf type {@code gps_data.LocationXY}
     */
    public  static final class LocationXY extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gps_data.LocationXY)
        LocationXYOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use LocationXY.newBuilder() to construct.
      private LocationXY(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private LocationXY() {
        x_ = "";
        y_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private LocationXY(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                x_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                y_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pbtest.internal_static_gps_data_LocationXY_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pbtest.internal_static_gps_data_LocationXY_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pbtest.gps_data.LocationXY.class, Pbtest.gps_data.LocationXY.Builder.class);
      }

      public static final int X_FIELD_NUMBER = 1;
      private volatile java.lang.Object x_;
      /**
       * <code>string x = 1;</code>
       */
      public java.lang.String getX() {
        java.lang.Object ref = x_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          x_ = s;
          return s;
        }
      }
      /**
       * <code>string x = 1;</code>
       */
      public com.google.protobuf.ByteString
          getXBytes() {
        java.lang.Object ref = x_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          x_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int Y_FIELD_NUMBER = 2;
      private volatile java.lang.Object y_;
      /**
       * <code>string y = 2;</code>
       */
      public java.lang.String getY() {
        java.lang.Object ref = y_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          y_ = s;
          return s;
        }
      }
      /**
       * <code>string y = 2;</code>
       */
      public com.google.protobuf.ByteString
          getYBytes() {
        java.lang.Object ref = y_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          y_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getXBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, x_);
        }
        if (!getYBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, y_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getXBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, x_);
        }
        if (!getYBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, y_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Pbtest.gps_data.LocationXY)) {
          return super.equals(obj);
        }
        Pbtest.gps_data.LocationXY other = (Pbtest.gps_data.LocationXY) obj;

        boolean result = true;
        result = result && getX()
            .equals(other.getX());
        result = result && getY()
            .equals(other.getY());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getX().hashCode();
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getY().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Pbtest.gps_data.LocationXY parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Pbtest.gps_data.LocationXY parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Pbtest.gps_data.LocationXY parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Pbtest.gps_data.LocationXY parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Pbtest.gps_data.LocationXY prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gps_data.LocationXY}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gps_data.LocationXY)
          Pbtest.gps_data.LocationXYOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Pbtest.internal_static_gps_data_LocationXY_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Pbtest.internal_static_gps_data_LocationXY_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Pbtest.gps_data.LocationXY.class, Pbtest.gps_data.LocationXY.Builder.class);
        }

        // Construct using Pbtest.gps_data.LocationXY.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          x_ = "";

          y_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Pbtest.internal_static_gps_data_LocationXY_descriptor;
        }

        public Pbtest.gps_data.LocationXY getDefaultInstanceForType() {
          return Pbtest.gps_data.LocationXY.getDefaultInstance();
        }

        public Pbtest.gps_data.LocationXY build() {
          Pbtest.gps_data.LocationXY result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Pbtest.gps_data.LocationXY buildPartial() {
          Pbtest.gps_data.LocationXY result = new Pbtest.gps_data.LocationXY(this);
          result.x_ = x_;
          result.y_ = y_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Pbtest.gps_data.LocationXY) {
            return mergeFrom((Pbtest.gps_data.LocationXY)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Pbtest.gps_data.LocationXY other) {
          if (other == Pbtest.gps_data.LocationXY.getDefaultInstance()) return this;
          if (!other.getX().isEmpty()) {
            x_ = other.x_;
            onChanged();
          }
          if (!other.getY().isEmpty()) {
            y_ = other.y_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Pbtest.gps_data.LocationXY parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Pbtest.gps_data.LocationXY) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object x_ = "";
        /**
         * <code>string x = 1;</code>
         */
        public java.lang.String getX() {
          java.lang.Object ref = x_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            x_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string x = 1;</code>
         */
        public com.google.protobuf.ByteString
            getXBytes() {
          java.lang.Object ref = x_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            x_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string x = 1;</code>
         */
        public Builder setX(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string x = 1;</code>
         */
        public Builder clearX() {
          
          x_ = getDefaultInstance().getX();
          onChanged();
          return this;
        }
        /**
         * <code>string x = 1;</code>
         */
        public Builder setXBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          x_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object y_ = "";
        /**
         * <code>string y = 2;</code>
         */
        public java.lang.String getY() {
          java.lang.Object ref = y_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            y_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string y = 2;</code>
         */
        public com.google.protobuf.ByteString
            getYBytes() {
          java.lang.Object ref = y_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            y_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string y = 2;</code>
         */
        public Builder setY(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string y = 2;</code>
         */
        public Builder clearY() {
          
          y_ = getDefaultInstance().getY();
          onChanged();
          return this;
        }
        /**
         * <code>string y = 2;</code>
         */
        public Builder setYBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          y_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gps_data.LocationXY)
      }

      // @@protoc_insertion_point(class_scope:gps_data.LocationXY)
      private static final Pbtest.gps_data.LocationXY DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Pbtest.gps_data.LocationXY();
      }

      public static Pbtest.gps_data.LocationXY getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<LocationXY>
          PARSER = new com.google.protobuf.AbstractParser<LocationXY>() {
        public LocationXY parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LocationXY(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<LocationXY> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<LocationXY> getParserForType() {
        return PARSER;
      }

      public Pbtest.gps_data.LocationXY getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TERMINALID_FIELD_NUMBER = 2;
    private volatile java.lang.Object terminalId_;
    /**
     * <code>string terminalId = 2;</code>
     */
    public java.lang.String getTerminalId() {
      java.lang.Object ref = terminalId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        terminalId_ = s;
        return s;
      }
    }
    /**
     * <code>string terminalId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTerminalIdBytes() {
      java.lang.Object ref = terminalId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        terminalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATATIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object dataTime_;
    /**
     * <code>string dataTime = 3;</code>
     */
    public java.lang.String getDataTime() {
      java.lang.Object ref = dataTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataTime_ = s;
        return s;
      }
    }
    /**
     * <code>string dataTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataTimeBytes() {
      java.lang.Object ref = dataTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LON_FIELD_NUMBER = 4;
    private double lon_;
    /**
     * <code>double lon = 4;</code>
     */
    public double getLon() {
      return lon_;
    }

    public static final int LAT_FIELD_NUMBER = 5;
    private double lat_;
    /**
     * <code>double lat = 5;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int SPEED_FIELD_NUMBER = 6;
    private float speed_;
    /**
     * <code>float speed = 6;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 7;
    private int altitude_;
    /**
     * <code>int32 altitude = 7;</code>
     */
    public int getAltitude() {
      return altitude_;
    }

    public static final int LOCTYPE_FIELD_NUMBER = 8;
    private int locType_;
    /**
     * <code>int32 locType = 8;</code>
     */
    public int getLocType() {
      return locType_;
    }

    public static final int GPSSTATUS_FIELD_NUMBER = 9;
    private int gpsStatus_;
    /**
     * <code>int32 gpsStatus = 9;</code>
     */
    public int getGpsStatus() {
      return gpsStatus_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 10;
    private float direction_;
    /**
     * <code>float direction = 10;</code>
     */
    public float getDirection() {
      return direction_;
    }

    public static final int SATELLITE_FIELD_NUMBER = 11;
    private int satellite_;
    /**
     * <code>int32 satellite = 11;</code>
     */
    public int getSatellite() {
      return satellite_;
    }

    public static final int TESTFIELD1_FIELD_NUMBER = 12;
    private long testField1_;
    /**
     * <code>int64 testField1 = 12;</code>
     */
    public long getTestField1() {
      return testField1_;
    }

    public static final int LOCXY_FIELD_NUMBER = 13;
    private Pbtest.gps_data.LocationXY locXY_;
    /**
     * <code>.gps_data.LocationXY locXY = 13;</code>
     */
    public boolean hasLocXY() {
      return locXY_ != null;
    }
    /**
     * <code>.gps_data.LocationXY locXY = 13;</code>
     */
    public Pbtest.gps_data.LocationXY getLocXY() {
      return locXY_ == null ? Pbtest.gps_data.LocationXY.getDefaultInstance() : locXY_;
    }
    /**
     * <code>.gps_data.LocationXY locXY = 13;</code>
     */
    public Pbtest.gps_data.LocationXYOrBuilder getLocXYOrBuilder() {
      return getLocXY();
    }

    public static final int SATELLITETYPE_FIELD_NUMBER = 14;
    private int satelliteType_;
    /**
     * <code>.gps_data.SatelliteType satelliteType = 14;</code>
     */
    public int getSatelliteTypeValue() {
      return satelliteType_;
    }
    /**
     * <code>.gps_data.SatelliteType satelliteType = 14;</code>
     */
    public Pbtest.gps_data.SatelliteType getSatelliteType() {
      Pbtest.gps_data.SatelliteType result = Pbtest.gps_data.SatelliteType.valueOf(satelliteType_);
      return result == null ? Pbtest.gps_data.SatelliteType.UNRECOGNIZED : result;
    }

    public static final int XYS_FIELD_NUMBER = 15;
    private java.util.List<java.lang.Integer> xys_;
    /**
     * <code>repeated int32 xys = 15;</code>
     */
    public java.util.List<java.lang.Integer>
        getXysList() {
      return xys_;
    }
    /**
     * <code>repeated int32 xys = 15;</code>
     */
    public int getXysCount() {
      return xys_.size();
    }
    /**
     * <code>repeated int32 xys = 15;</code>
     */
    public int getXys(int index) {
      return xys_.get(index);
    }
    private int xysMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getTerminalIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, terminalId_);
      }
      if (!getDataTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataTime_);
      }
      if (lon_ != 0D) {
        output.writeDouble(4, lon_);
      }
      if (lat_ != 0D) {
        output.writeDouble(5, lat_);
      }
      if (speed_ != 0F) {
        output.writeFloat(6, speed_);
      }
      if (altitude_ != 0) {
        output.writeInt32(7, altitude_);
      }
      if (locType_ != 0) {
        output.writeInt32(8, locType_);
      }
      if (gpsStatus_ != 0) {
        output.writeInt32(9, gpsStatus_);
      }
      if (direction_ != 0F) {
        output.writeFloat(10, direction_);
      }
      if (satellite_ != 0) {
        output.writeInt32(11, satellite_);
      }
      if (testField1_ != 0L) {
        output.writeInt64(12, testField1_);
      }
      if (locXY_ != null) {
        output.writeMessage(13, getLocXY());
      }
      if (satelliteType_ != Pbtest.gps_data.SatelliteType.DEFAULT.getNumber()) {
        output.writeEnum(14, satelliteType_);
      }
      if (getXysList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(xysMemoizedSerializedSize);
      }
      for (int i = 0; i < xys_.size(); i++) {
        output.writeInt32NoTag(xys_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getTerminalIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, terminalId_);
      }
      if (!getDataTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataTime_);
      }
      if (lon_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, lon_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, lat_);
      }
      if (speed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, speed_);
      }
      if (altitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, altitude_);
      }
      if (locType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, locType_);
      }
      if (gpsStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, gpsStatus_);
      }
      if (direction_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, direction_);
      }
      if (satellite_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, satellite_);
      }
      if (testField1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, testField1_);
      }
      if (locXY_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getLocXY());
      }
      if (satelliteType_ != Pbtest.gps_data.SatelliteType.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(14, satelliteType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < xys_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(xys_.get(i));
        }
        size += dataSize;
        if (!getXysList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        xysMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pbtest.gps_data)) {
        return super.equals(obj);
      }
      Pbtest.gps_data other = (Pbtest.gps_data) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTerminalId()
          .equals(other.getTerminalId());
      result = result && getDataTime()
          .equals(other.getDataTime());
      result = result && (
          java.lang.Double.doubleToLongBits(getLon())
          == java.lang.Double.doubleToLongBits(
              other.getLon()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLat())
          == java.lang.Double.doubleToLongBits(
              other.getLat()));
      result = result && (
          java.lang.Float.floatToIntBits(getSpeed())
          == java.lang.Float.floatToIntBits(
              other.getSpeed()));
      result = result && (getAltitude()
          == other.getAltitude());
      result = result && (getLocType()
          == other.getLocType());
      result = result && (getGpsStatus()
          == other.getGpsStatus());
      result = result && (
          java.lang.Float.floatToIntBits(getDirection())
          == java.lang.Float.floatToIntBits(
              other.getDirection()));
      result = result && (getSatellite()
          == other.getSatellite());
      result = result && (getTestField1()
          == other.getTestField1());
      result = result && (hasLocXY() == other.hasLocXY());
      if (hasLocXY()) {
        result = result && getLocXY()
            .equals(other.getLocXY());
      }
      result = result && satelliteType_ == other.satelliteType_;
      result = result && getXysList()
          .equals(other.getXysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TERMINALID_FIELD_NUMBER;
      hash = (53 * hash) + getTerminalId().hashCode();
      hash = (37 * hash) + DATATIME_FIELD_NUMBER;
      hash = (53 * hash) + getDataTime().hashCode();
      hash = (37 * hash) + LON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLon()));
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getAltitude();
      hash = (37 * hash) + LOCTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLocType();
      hash = (37 * hash) + GPSSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getGpsStatus();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDirection());
      hash = (37 * hash) + SATELLITE_FIELD_NUMBER;
      hash = (53 * hash) + getSatellite();
      hash = (37 * hash) + TESTFIELD1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTestField1());
      if (hasLocXY()) {
        hash = (37 * hash) + LOCXY_FIELD_NUMBER;
        hash = (53 * hash) + getLocXY().hashCode();
      }
      hash = (37 * hash) + SATELLITETYPE_FIELD_NUMBER;
      hash = (53 * hash) + satelliteType_;
      if (getXysCount() > 0) {
        hash = (37 * hash) + XYS_FIELD_NUMBER;
        hash = (53 * hash) + getXysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pbtest.gps_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pbtest.gps_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pbtest.gps_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pbtest.gps_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pbtest.gps_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pbtest.gps_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pbtest.gps_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pbtest.gps_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pbtest.gps_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Pbtest.gps_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pbtest.gps_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pbtest.gps_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pbtest.gps_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gps_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gps_data)
        Pbtest.gps_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pbtest.internal_static_gps_data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pbtest.internal_static_gps_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pbtest.gps_data.class, Pbtest.gps_data.Builder.class);
      }

      // Construct using Pbtest.gps_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        terminalId_ = "";

        dataTime_ = "";

        lon_ = 0D;

        lat_ = 0D;

        speed_ = 0F;

        altitude_ = 0;

        locType_ = 0;

        gpsStatus_ = 0;

        direction_ = 0F;

        satellite_ = 0;

        testField1_ = 0L;

        if (locXYBuilder_ == null) {
          locXY_ = null;
        } else {
          locXY_ = null;
          locXYBuilder_ = null;
        }
        satelliteType_ = 0;

        xys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Pbtest.internal_static_gps_data_descriptor;
      }

      public Pbtest.gps_data getDefaultInstanceForType() {
        return Pbtest.gps_data.getDefaultInstance();
      }

      public Pbtest.gps_data build() {
        Pbtest.gps_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Pbtest.gps_data buildPartial() {
        Pbtest.gps_data result = new Pbtest.gps_data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.terminalId_ = terminalId_;
        result.dataTime_ = dataTime_;
        result.lon_ = lon_;
        result.lat_ = lat_;
        result.speed_ = speed_;
        result.altitude_ = altitude_;
        result.locType_ = locType_;
        result.gpsStatus_ = gpsStatus_;
        result.direction_ = direction_;
        result.satellite_ = satellite_;
        result.testField1_ = testField1_;
        if (locXYBuilder_ == null) {
          result.locXY_ = locXY_;
        } else {
          result.locXY_ = locXYBuilder_.build();
        }
        result.satelliteType_ = satelliteType_;
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          xys_ = java.util.Collections.unmodifiableList(xys_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.xys_ = xys_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pbtest.gps_data) {
          return mergeFrom((Pbtest.gps_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pbtest.gps_data other) {
        if (other == Pbtest.gps_data.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTerminalId().isEmpty()) {
          terminalId_ = other.terminalId_;
          onChanged();
        }
        if (!other.getDataTime().isEmpty()) {
          dataTime_ = other.dataTime_;
          onChanged();
        }
        if (other.getLon() != 0D) {
          setLon(other.getLon());
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getSpeed() != 0F) {
          setSpeed(other.getSpeed());
        }
        if (other.getAltitude() != 0) {
          setAltitude(other.getAltitude());
        }
        if (other.getLocType() != 0) {
          setLocType(other.getLocType());
        }
        if (other.getGpsStatus() != 0) {
          setGpsStatus(other.getGpsStatus());
        }
        if (other.getDirection() != 0F) {
          setDirection(other.getDirection());
        }
        if (other.getSatellite() != 0) {
          setSatellite(other.getSatellite());
        }
        if (other.getTestField1() != 0L) {
          setTestField1(other.getTestField1());
        }
        if (other.hasLocXY()) {
          mergeLocXY(other.getLocXY());
        }
        if (other.satelliteType_ != 0) {
          setSatelliteTypeValue(other.getSatelliteTypeValue());
        }
        if (!other.xys_.isEmpty()) {
          if (xys_.isEmpty()) {
            xys_ = other.xys_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureXysIsMutable();
            xys_.addAll(other.xys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Pbtest.gps_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Pbtest.gps_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object terminalId_ = "";
      /**
       * <code>string terminalId = 2;</code>
       */
      public java.lang.String getTerminalId() {
        java.lang.Object ref = terminalId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          terminalId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string terminalId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTerminalIdBytes() {
        java.lang.Object ref = terminalId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          terminalId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string terminalId = 2;</code>
       */
      public Builder setTerminalId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        terminalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string terminalId = 2;</code>
       */
      public Builder clearTerminalId() {
        
        terminalId_ = getDefaultInstance().getTerminalId();
        onChanged();
        return this;
      }
      /**
       * <code>string terminalId = 2;</code>
       */
      public Builder setTerminalIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        terminalId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataTime_ = "";
      /**
       * <code>string dataTime = 3;</code>
       */
      public java.lang.String getDataTime() {
        java.lang.Object ref = dataTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataTimeBytes() {
        java.lang.Object ref = dataTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataTime = 3;</code>
       */
      public Builder setDataTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataTime = 3;</code>
       */
      public Builder clearDataTime() {
        
        dataTime_ = getDefaultInstance().getDataTime();
        onChanged();
        return this;
      }
      /**
       * <code>string dataTime = 3;</code>
       */
      public Builder setDataTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataTime_ = value;
        onChanged();
        return this;
      }

      private double lon_ ;
      /**
       * <code>double lon = 4;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>double lon = 4;</code>
       */
      public Builder setLon(double value) {
        
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double lon = 4;</code>
       */
      public Builder clearLon() {
        
        lon_ = 0D;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <code>double lat = 5;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>double lat = 5;</code>
       */
      public Builder setLat(double value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double lat = 5;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0D;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>float speed = 6;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>float speed = 6;</code>
       */
      public Builder setSpeed(float value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float speed = 6;</code>
       */
      public Builder clearSpeed() {
        
        speed_ = 0F;
        onChanged();
        return this;
      }

      private int altitude_ ;
      /**
       * <code>int32 altitude = 7;</code>
       */
      public int getAltitude() {
        return altitude_;
      }
      /**
       * <code>int32 altitude = 7;</code>
       */
      public Builder setAltitude(int value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 altitude = 7;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0;
        onChanged();
        return this;
      }

      private int locType_ ;
      /**
       * <code>int32 locType = 8;</code>
       */
      public int getLocType() {
        return locType_;
      }
      /**
       * <code>int32 locType = 8;</code>
       */
      public Builder setLocType(int value) {
        
        locType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locType = 8;</code>
       */
      public Builder clearLocType() {
        
        locType_ = 0;
        onChanged();
        return this;
      }

      private int gpsStatus_ ;
      /**
       * <code>int32 gpsStatus = 9;</code>
       */
      public int getGpsStatus() {
        return gpsStatus_;
      }
      /**
       * <code>int32 gpsStatus = 9;</code>
       */
      public Builder setGpsStatus(int value) {
        
        gpsStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 gpsStatus = 9;</code>
       */
      public Builder clearGpsStatus() {
        
        gpsStatus_ = 0;
        onChanged();
        return this;
      }

      private float direction_ ;
      /**
       * <code>float direction = 10;</code>
       */
      public float getDirection() {
        return direction_;
      }
      /**
       * <code>float direction = 10;</code>
       */
      public Builder setDirection(float value) {
        
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float direction = 10;</code>
       */
      public Builder clearDirection() {
        
        direction_ = 0F;
        onChanged();
        return this;
      }

      private int satellite_ ;
      /**
       * <code>int32 satellite = 11;</code>
       */
      public int getSatellite() {
        return satellite_;
      }
      /**
       * <code>int32 satellite = 11;</code>
       */
      public Builder setSatellite(int value) {
        
        satellite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 satellite = 11;</code>
       */
      public Builder clearSatellite() {
        
        satellite_ = 0;
        onChanged();
        return this;
      }

      private long testField1_ ;
      /**
       * <code>int64 testField1 = 12;</code>
       */
      public long getTestField1() {
        return testField1_;
      }
      /**
       * <code>int64 testField1 = 12;</code>
       */
      public Builder setTestField1(long value) {
        
        testField1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 testField1 = 12;</code>
       */
      public Builder clearTestField1() {
        
        testField1_ = 0L;
        onChanged();
        return this;
      }

      private Pbtest.gps_data.LocationXY locXY_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Pbtest.gps_data.LocationXY, Pbtest.gps_data.LocationXY.Builder, Pbtest.gps_data.LocationXYOrBuilder> locXYBuilder_;
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public boolean hasLocXY() {
        return locXYBuilder_ != null || locXY_ != null;
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Pbtest.gps_data.LocationXY getLocXY() {
        if (locXYBuilder_ == null) {
          return locXY_ == null ? Pbtest.gps_data.LocationXY.getDefaultInstance() : locXY_;
        } else {
          return locXYBuilder_.getMessage();
        }
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Builder setLocXY(Pbtest.gps_data.LocationXY value) {
        if (locXYBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          locXY_ = value;
          onChanged();
        } else {
          locXYBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Builder setLocXY(
          Pbtest.gps_data.LocationXY.Builder builderForValue) {
        if (locXYBuilder_ == null) {
          locXY_ = builderForValue.build();
          onChanged();
        } else {
          locXYBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Builder mergeLocXY(Pbtest.gps_data.LocationXY value) {
        if (locXYBuilder_ == null) {
          if (locXY_ != null) {
            locXY_ =
              Pbtest.gps_data.LocationXY.newBuilder(locXY_).mergeFrom(value).buildPartial();
          } else {
            locXY_ = value;
          }
          onChanged();
        } else {
          locXYBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Builder clearLocXY() {
        if (locXYBuilder_ == null) {
          locXY_ = null;
          onChanged();
        } else {
          locXY_ = null;
          locXYBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Pbtest.gps_data.LocationXY.Builder getLocXYBuilder() {
        
        onChanged();
        return getLocXYFieldBuilder().getBuilder();
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      public Pbtest.gps_data.LocationXYOrBuilder getLocXYOrBuilder() {
        if (locXYBuilder_ != null) {
          return locXYBuilder_.getMessageOrBuilder();
        } else {
          return locXY_ == null ?
              Pbtest.gps_data.LocationXY.getDefaultInstance() : locXY_;
        }
      }
      /**
       * <code>.gps_data.LocationXY locXY = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Pbtest.gps_data.LocationXY, Pbtest.gps_data.LocationXY.Builder, Pbtest.gps_data.LocationXYOrBuilder> 
          getLocXYFieldBuilder() {
        if (locXYBuilder_ == null) {
          locXYBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Pbtest.gps_data.LocationXY, Pbtest.gps_data.LocationXY.Builder, Pbtest.gps_data.LocationXYOrBuilder>(
                  getLocXY(),
                  getParentForChildren(),
                  isClean());
          locXY_ = null;
        }
        return locXYBuilder_;
      }

      private int satelliteType_ = 0;
      /**
       * <code>.gps_data.SatelliteType satelliteType = 14;</code>
       */
      public int getSatelliteTypeValue() {
        return satelliteType_;
      }
      /**
       * <code>.gps_data.SatelliteType satelliteType = 14;</code>
       */
      public Builder setSatelliteTypeValue(int value) {
        satelliteType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.gps_data.SatelliteType satelliteType = 14;</code>
       */
      public Pbtest.gps_data.SatelliteType getSatelliteType() {
        Pbtest.gps_data.SatelliteType result = Pbtest.gps_data.SatelliteType.valueOf(satelliteType_);
        return result == null ? Pbtest.gps_data.SatelliteType.UNRECOGNIZED : result;
      }
      /**
       * <code>.gps_data.SatelliteType satelliteType = 14;</code>
       */
      public Builder setSatelliteType(Pbtest.gps_data.SatelliteType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        satelliteType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.gps_data.SatelliteType satelliteType = 14;</code>
       */
      public Builder clearSatelliteType() {
        
        satelliteType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> xys_ = java.util.Collections.emptyList();
      private void ensureXysIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          xys_ = new java.util.ArrayList<java.lang.Integer>(xys_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public java.util.List<java.lang.Integer>
          getXysList() {
        return java.util.Collections.unmodifiableList(xys_);
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public int getXysCount() {
        return xys_.size();
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public int getXys(int index) {
        return xys_.get(index);
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public Builder setXys(
          int index, int value) {
        ensureXysIsMutable();
        xys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public Builder addXys(int value) {
        ensureXysIsMutable();
        xys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public Builder addAllXys(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureXysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, xys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 xys = 15;</code>
       */
      public Builder clearXys() {
        xys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gps_data)
    }

    // @@protoc_insertion_point(class_scope:gps_data)
    private static final Pbtest.gps_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pbtest.gps_data();
    }

    public static Pbtest.gps_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gps_data>
        PARSER = new com.google.protobuf.AbstractParser<gps_data>() {
      public gps_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gps_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gps_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gps_data> getParserForType() {
      return PARSER;
    }

    public Pbtest.gps_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_data_LocationXY_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_data_LocationXY_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014pbtest.proto\"\234\003\n\010gps_data\022\n\n\002id\030\001 \001(\003\022" +
      "\022\n\nterminalId\030\002 \001(\t\022\020\n\010dataTime\030\003 \001(\t\022\013\n" +
      "\003lon\030\004 \001(\001\022\013\n\003lat\030\005 \001(\001\022\r\n\005speed\030\006 \001(\002\022\020" +
      "\n\010altitude\030\007 \001(\005\022\017\n\007locType\030\010 \001(\005\022\021\n\tgps" +
      "Status\030\t \001(\005\022\021\n\tdirection\030\n \001(\002\022\021\n\tsatel" +
      "lite\030\013 \001(\005\022\022\n\ntestField1\030\014 \001(\003\022#\n\005locXY\030" +
      "\r \001(\0132\024.gps_data.LocationXY\022.\n\rsatellite" +
      "Type\030\016 \001(\0162\027.gps_data.SatelliteType\022\013\n\003x" +
      "ys\030\017 \003(\005\032\"\n\nLocationXY\022\t\n\001x\030\001 \001(\t\022\t\n\001y\030\002" +
      " \001(\t\"?\n\rSatelliteType\022\013\n\007DEFAULT\020\000\022\007\n\003GP" +
      "S\020\001\022\013\n\007GLONASS\020\002\022\013\n\007GALILEO\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gps_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gps_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_data_descriptor,
        new java.lang.String[] { "Id", "TerminalId", "DataTime", "Lon", "Lat", "Speed", "Altitude", "LocType", "GpsStatus", "Direction", "Satellite", "TestField1", "LocXY", "SatelliteType", "Xys", });
    internal_static_gps_data_LocationXY_descriptor =
      internal_static_gps_data_descriptor.getNestedTypes().get(0);
    internal_static_gps_data_LocationXY_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_data_LocationXY_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
